In [10]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv("Datas/clear_encoded_data.csv")
df

,amines,alcohol,ether,alkyl halide,thiol,aldehyde,ketone,amides,sulfide,carbodiimides,...,azocompound,sulfoxide,azido,nitroso,phospate,phospite,isothio,thioamide,aromatic,cycle
0,1,1,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,1,2
1,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,3,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
3,2,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62082,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,1
62083,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,1
62084,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,3
62085,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
62086,1,2,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [17]:
def variance(X : np.array) :
    mean = np.mean(X)
    sum = np.sum([(xi - mean)**2 for xi in X])
    return sum/len(X)

In [18]:
var_list = [(cols, variance(df[cols])) for cols in df.columns]
filetered_columns = [i for i, j in var_list if j > 0.5]
filetered_columns

['amines', 'ether', 'aldehyde', 'aromatic', 'cycle']

In [19]:
df = df[filetered_columns]
df

       amines  ether  aldehyde  aromatic  cycle
0           1      0         1         1      2
1           1      0         0         1      0
2           3      0         1         0      2
3           2      0         1         1      0
4           1      0         0         2      2
...       ...    ...       ...       ...    ...
62082       1      1         0         2      1
62083       1      0         0         2      1
62084       2      0         0         1      3
62085       2      0         0         0      2
62086       1      1         0         1      0

[62087 rows x 5 columns]

In [22]:
df.to_csv("Datas/selected_data.csv", index=False)